[0.000000] (-) TimerEvent: {}
[0.000339] (-) JobUnselected: {'identifier': 'xarm_api'}
[0.001211] (-) JobUnselected: {'identifier': 'xarm_controller'}
[0.001279] (-) JobUnselected: {'identifier': 'xarm_description'}
[0.001449] (-) JobUnselected: {'identifier': 'xarm_gazebo'}
[0.001475] (-) JobUnselected: {'identifier': 'xarm_moveit_config'}
[0.001640] (-) JobUnselected: {'identifier': 'xarm_moveit_servo'}
[0.001687] (-) JobUnselected: {'identifier': 'xarm_msgs'}
[0.001738] (-) JobUnselected: {'identifier': 'xarm_planner'}
[0.001751] (-) JobUnselected: {'identifier': 'xarm_sdk'}
[0.001765] (detection_node) JobQueued: {'identifier': 'detection_node', 'dependencies': OrderedDict()}
[0.001780] (detection_node) JobStarted: {'identifier': 'detection_node'}
[0.099853] (-) TimerEvent: {}
[0.200227] (-) TimerEvent: {}
[0.291507] (detection_node) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build\n    setup_py_data = get_setup_data(self.context.pkg, env)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/__init__.py", line 20, in get_setup_data\n    return dict(pkg.metadata[key](env))\n  File "/usr/lib/python3/dist-packages/colcon_ros/package_augmentation/ros_ament_python.py", line 57, in getter\n    return get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 241, in get_setup_information\n    _setup_information_cache[hashable_env] = _get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 288, in _get_setup_information\n    result = subprocess.run(\n  File "/usr/lib/python3.8/subprocess.py", line 516, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/python3\', \'-c\', \'import sys;from contextlib import suppress;exec("with suppress(ImportError):    from setuptools.extern.packaging.specifiers    import SpecifierSet");exec("with suppress(ImportError):    from packaging.specifiers import SpecifierSet");from distutils.core import run_setup;dist = run_setup(    \\\'setup.py\\\', script_args=(\\\'--dry-run\\\',), stop_after=\\\'config\\\');skip_keys = (\\\'cmdclass\\\', \\\'distclass\\\', \\\'ext_modules\\\', \\\'metadata\\\');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith(\\\'_\\\') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data[\\\'metadata\\\'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in (\\\'license_files\\\', \\\'provides_extras\\\')};sys.stdout.buffer.write(repr(data).encode(\\\'utf-8\\\'))\']\' returned non-zero exit status 1.\n'}
[0.291970] (detection_node) JobEnded: {'identifier': 'detection_node', 'rc': 1}
[0.300330] (-) TimerEvent: {}
[0.302025] (-) EventReactorShutdown: {}
